Invalid HTTP_HOST header: 'DESKTOP-KB0D89T:8000'. You may need to add 'desktop-kb0d89t' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "C:\Users\Windows\AndroidStudioProjects\LaboratorioCalificado003\BACKEND-FINANCIERA\env\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Windows\AndroidStudioProjects\LaboratorioCalificado003\BACKEND-FINANCIERA\env\Lib\site-packages\django\utils\deprecation.py", line 128, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Windows\AndroidStudioProjects\LaboratorioCalificado003\BACKEND-FINANCIERA\env\Lib\site-packages\django\middleware\common.py", line 48, in process_request
    host = request.get_host()
           ^^^^^^^^^^^^^^^^^^
  File "C:\Users\Windows\AndroidStudioProjects\LaboratorioCalificado003\BACKEND-FINANCIERA\env\Lib\site-packages\django\http\request.py", line 151, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'DESKTOP-KB0D89T:8000'. You may need to add 'desktop-kb0d89t' to ALLOWED_HOSTS.
Internal Server Error: /api/usuarios/
Traceback (most recent call last):
  File "C:\Users\Windows\AndroidStudioProjects\LaboratorioCalificado003\BACKEND-FINANCIERA\env\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Windows\AndroidStudioProjects\LaboratorioCalificado003\BACKEND-FINANCIERA\env\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Windows\AndroidStudioProjects\LaboratorioCalificado003\BACKEND-FINANCIERA\env\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Windows\AndroidStudioProjects\LaboratorioCalificado003\BACKEND-FINANCIERA\env\Lib\site-packages\rest_framework\viewsets.py", line 124, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Windows\AndroidStudioProjects\LaboratorioCalificado003\BACKEND-FINANCIERA\env\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Windows\AndroidStudioProjects\LaboratorioCalificado003\BACKEND-FINANCIERA\env\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\Windows\AndroidStudioProjects\LaboratorioCalificado003\BACKEND-FINANCIERA\env\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\Windows\AndroidStudioProjects\LaboratorioCalificado003\BACKEND-FINANCIERA\env\Lib\site-packages\rest_framework\views.py", line 497, in dispatch
    self.initial(request, *args, **kwargs)
  File "C:\Users\Windows\AndroidStudioProjects\LaboratorioCalificado003\BACKEND-FINANCIERA\env\Lib\site-packages\rest_framework\views.py", line 415, in initial
    self.check_permissions(request)
  File "C:\Users\Windows\AndroidStudioProjects\LaboratorioCalificado003\BACKEND-FINANCIERA\env\Lib\site-packages\rest_framework\views.py", line 331, in check_permissions
    for permission in self.get_permissions():
                      ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Windows\AndroidStudioProjects\LaboratorioCalificado003\BACKEND-FINANCIERA\usuarios\views.py", line 26, in get_permissions
    if self.request.user.rol == "ADMIN":
       ^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'AnonymousUser' object has no attribute 'rol'
"GET /api/usuarios/ HTTP/1.1" 500 102021
Internal Server Error: /api/usuarios/
Traceback (most recent call last):
  File "C:\Users\Windows\AndroidStudioProjects\LaboratorioCalificado003\BACKEND-FINANCIERA\env\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Windows\AndroidStudioProjects\LaboratorioCalificado003\BACKEND-FINANCIERA\env\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Windows\AndroidStudioProjects\LaboratorioCalificado003\BACKEND-FINANCIERA\env\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Windows\AndroidStudioProjects\LaboratorioCalificado003\BACKEND-FINANCIERA\env\Lib\site-packages\rest_framework\viewsets.py", line 124, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Windows\AndroidStudioProjects\LaboratorioCalificado003\BACKEND-FINANCIERA\env\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Windows\AndroidStudioProjects\LaboratorioCalificado003\BACKEND-FINANCIERA\env\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\Windows\AndroidStudioProjects\LaboratorioCalificado003\BACKEND-FINANCIERA\env\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\Windows\AndroidStudioProjects\LaboratorioCalificado003\BACKEND-FINANCIERA\env\Lib\site-packages\rest_framework\views.py", line 497, in dispatch
    self.initial(request, *args, **kwargs)
  File "C:\Users\Windows\AndroidStudioProjects\LaboratorioCalificado003\BACKEND-FINANCIERA\env\Lib\site-packages\rest_framework\views.py", line 415, in initial
    self.check_permissions(request)
  File "C:\Users\Windows\AndroidStudioProjects\LaboratorioCalificado003\BACKEND-FINANCIERA\env\Lib\site-packages\rest_framework\views.py", line 331, in check_permissions
    for permission in self.get_permissions():
                      ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Windows\AndroidStudioProjects\LaboratorioCalificado003\BACKEND-FINANCIERA\usuarios\views.py", line 26, in get_permissions
    if self.request.user.rol == "ADMIN":
       ^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'User' object has no attribute 'rol'
"GET /api/usuarios/ HTTP/1.1" 500 102494
Internal Server Error: /api/usuarios/
Traceback (most recent call last):
  File "C:\Users\Windows\AndroidStudioProjects\LaboratorioCalificado003\BACKEND-FINANCIERA\env\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Windows\AndroidStudioProjects\LaboratorioCalificado003\BACKEND-FINANCIERA\env\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Windows\AndroidStudioProjects\LaboratorioCalificado003\BACKEND-FINANCIERA\env\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Windows\AndroidStudioProjects\LaboratorioCalificado003\BACKEND-FINANCIERA\env\Lib\site-packages\rest_framework\viewsets.py", line 124, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Windows\AndroidStudioProjects\LaboratorioCalificado003\BACKEND-FINANCIERA\env\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Windows\AndroidStudioProjects\LaboratorioCalificado003\BACKEND-FINANCIERA\env\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\Windows\AndroidStudioProjects\LaboratorioCalificado003\BACKEND-FINANCIERA\env\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\Windows\AndroidStudioProjects\LaboratorioCalificado003\BACKEND-FINANCIERA\env\Lib\site-packages\rest_framework\views.py", line 497, in dispatch
    self.initial(request, *args, **kwargs)
  File "C:\Users\Windows\AndroidStudioProjects\LaboratorioCalificado003\BACKEND-FINANCIERA\env\Lib\site-packages\rest_framework\views.py", line 415, in initial
    self.check_permissions(request)
  File "C:\Users\Windows\AndroidStudioProjects\LaboratorioCalificado003\BACKEND-FINANCIERA\env\Lib\site-packages\rest_framework\views.py", line 331, in check_permissions
    for permission in self.get_permissions():
                      ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Windows\AndroidStudioProjects\LaboratorioCalificado003\BACKEND-FINANCIERA\usuarios\views.py", line 26, in get_permissions
    if self.request.user.rol == "ADMIN":
       ^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'User' object has no attribute 'rol'
"GET /api/usuarios/ HTTP/1.1" 500 102346
Internal Server Error: /api/usuarios/
Traceback (most recent call last):
  File "C:\Users\Windows\AndroidStudioProjects\LaboratorioCalificado003\BACKEND-FINANCIERA\env\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Windows\AndroidStudioProjects\LaboratorioCalificado003\BACKEND-FINANCIERA\env\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Windows\AndroidStudioProjects\LaboratorioCalificado003\BACKEND-FINANCIERA\env\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Windows\AndroidStudioProjects\LaboratorioCalificado003\BACKEND-FINANCIERA\env\Lib\site-packages\rest_framework\viewsets.py", line 124, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Windows\AndroidStudioProjects\LaboratorioCalificado003\BACKEND-FINANCIERA\env\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Windows\AndroidStudioProjects\LaboratorioCalificado003\BACKEND-FINANCIERA\env\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\Windows\AndroidStudioProjects\LaboratorioCalificado003\BACKEND-FINANCIERA\env\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\Windows\AndroidStudioProjects\LaboratorioCalificado003\BACKEND-FINANCIERA\env\Lib\site-packages\rest_framework\views.py", line 497, in dispatch
    self.initial(request, *args, **kwargs)
  File "C:\Users\Windows\AndroidStudioProjects\LaboratorioCalificado003\BACKEND-FINANCIERA\env\Lib\site-packages\rest_framework\views.py", line 415, in initial
    self.check_permissions(request)
  File "C:\Users\Windows\AndroidStudioProjects\LaboratorioCalificado003\BACKEND-FINANCIERA\env\Lib\site-packages\rest_framework\views.py", line 331, in check_permissions
    for permission in self.get_permissions():
                      ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Windows\AndroidStudioProjects\LaboratorioCalificado003\BACKEND-FINANCIERA\usuarios\views.py", line 26, in get_permissions
    if self.request.user.rol == "ADMIN":
       ^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'User' object has no attribute 'rol'
"GET /api/usuarios/ HTTP/1.1" 500 102346
Internal Server Error: /api/usuarios/
Traceback (most recent call last):
  File "C:\Users\Windows\AndroidStudioProjects\LaboratorioCalificado003\BACKEND-FINANCIERA\env\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Windows\AndroidStudioProjects\LaboratorioCalificado003\BACKEND-FINANCIERA\env\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Windows\AndroidStudioProjects\LaboratorioCalificado003\BACKEND-FINANCIERA\env\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Windows\AndroidStudioProjects\LaboratorioCalificado003\BACKEND-FINANCIERA\env\Lib\site-packages\rest_framework\viewsets.py", line 124, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Windows\AndroidStudioProjects\LaboratorioCalificado003\BACKEND-FINANCIERA\env\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Windows\AndroidStudioProjects\LaboratorioCalificado003\BACKEND-FINANCIERA\env\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\Windows\AndroidStudioProjects\LaboratorioCalificado003\BACKEND-FINANCIERA\env\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\Windows\AndroidStudioProjects\LaboratorioCalificado003\BACKEND-FINANCIERA\env\Lib\site-packages\rest_framework\views.py", line 497, in dispatch
    self.initial(request, *args, **kwargs)
  File "C:\Users\Windows\AndroidStudioProjects\LaboratorioCalificado003\BACKEND-FINANCIERA\env\Lib\site-packages\rest_framework\views.py", line 415, in initial
    self.check_permissions(request)
  File "C:\Users\Windows\AndroidStudioProjects\LaboratorioCalificado003\BACKEND-FINANCIERA\env\Lib\site-packages\rest_framework\views.py", line 331, in check_permissions
    for permission in self.get_permissions():
                      ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Windows\AndroidStudioProjects\LaboratorioCalificado003\BACKEND-FINANCIERA\usuarios\views.py", line 26, in get_permissions
    if self.request.user.rol == "ADMIN":
       ^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'User' object has no attribute 'rol'
"GET /api/usuarios/ HTTP/1.1" 500 102346
Internal Server Error: /api/usuarios/
Traceback (most recent call last):
  File "C:\Users\Windows\AndroidStudioProjects\LaboratorioCalificado003\BACKEND-FINANCIERA\env\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Windows\AndroidStudioProjects\LaboratorioCalificado003\BACKEND-FINANCIERA\env\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Windows\AndroidStudioProjects\LaboratorioCalificado003\BACKEND-FINANCIERA\env\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Windows\AndroidStudioProjects\LaboratorioCalificado003\BACKEND-FINANCIERA\env\Lib\site-packages\rest_framework\viewsets.py", line 124, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Windows\AndroidStudioProjects\LaboratorioCalificado003\BACKEND-FINANCIERA\env\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Windows\AndroidStudioProjects\LaboratorioCalificado003\BACKEND-FINANCIERA\env\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\Windows\AndroidStudioProjects\LaboratorioCalificado003\BACKEND-FINANCIERA\env\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\Windows\AndroidStudioProjects\LaboratorioCalificado003\BACKEND-FINANCIERA\env\Lib\site-packages\rest_framework\views.py", line 497, in dispatch
    self.initial(request, *args, **kwargs)
  File "C:\Users\Windows\AndroidStudioProjects\LaboratorioCalificado003\BACKEND-FINANCIERA\env\Lib\site-packages\rest_framework\views.py", line 415, in initial
    self.check_permissions(request)
  File "C:\Users\Windows\AndroidStudioProjects\LaboratorioCalificado003\BACKEND-FINANCIERA\env\Lib\site-packages\rest_framework\views.py", line 331, in check_permissions
    for permission in self.get_permissions():
                      ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Windows\AndroidStudioProjects\LaboratorioCalificado003\BACKEND-FINANCIERA\usuarios\views.py", line 26, in get_permissions
    if self.request.user.rol == "ADMIN":
       ^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'User' object has no attribute 'rol'
"GET /api/usuarios/ HTTP/1.1" 500 102346
Internal Server Error: /api/usuarios/
Traceback (most recent call last):
  File "C:\Users\Windows\AndroidStudioProjects\LaboratorioCalificado003\BACKEND-FINANCIERA\env\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Windows\AndroidStudioProjects\LaboratorioCalificado003\BACKEND-FINANCIERA\env\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Windows\AndroidStudioProjects\LaboratorioCalificado003\BACKEND-FINANCIERA\env\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Windows\AndroidStudioProjects\LaboratorioCalificado003\BACKEND-FINANCIERA\env\Lib\site-packages\rest_framework\viewsets.py", line 124, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Windows\AndroidStudioProjects\LaboratorioCalificado003\BACKEND-FINANCIERA\env\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Windows\AndroidStudioProjects\LaboratorioCalificado003\BACKEND-FINANCIERA\env\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\Windows\AndroidStudioProjects\LaboratorioCalificado003\BACKEND-FINANCIERA\env\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\Windows\AndroidStudioProjects\LaboratorioCalificado003\BACKEND-FINANCIERA\env\Lib\site-packages\rest_framework\views.py", line 497, in dispatch
    self.initial(request, *args, **kwargs)
  File "C:\Users\Windows\AndroidStudioProjects\LaboratorioCalificado003\BACKEND-FINANCIERA\env\Lib\site-packages\rest_framework\views.py", line 415, in initial
    self.check_permissions(request)
  File "C:\Users\Windows\AndroidStudioProjects\LaboratorioCalificado003\BACKEND-FINANCIERA\env\Lib\site-packages\rest_framework\views.py", line 331, in check_permissions
    for permission in self.get_permissions():
                      ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Windows\AndroidStudioProjects\LaboratorioCalificado003\BACKEND-FINANCIERA\usuarios\views.py", line 26, in get_permissions
    if self.request.user.rol == "ADMIN":
       ^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'User' object has no attribute 'rol'
"GET /api/usuarios/ HTTP/1.1" 500 102346
Internal Server Error: /api/usuarios/
Traceback (most recent call last):
  File "C:\Users\Windows\AndroidStudioProjects\LaboratorioCalificado003\BACKEND-FINANCIERA\env\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Windows\AndroidStudioProjects\LaboratorioCalificado003\BACKEND-FINANCIERA\env\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Windows\AndroidStudioProjects\LaboratorioCalificado003\BACKEND-FINANCIERA\env\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Windows\AndroidStudioProjects\LaboratorioCalificado003\BACKEND-FINANCIERA\env\Lib\site-packages\rest_framework\viewsets.py", line 124, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Windows\AndroidStudioProjects\LaboratorioCalificado003\BACKEND-FINANCIERA\env\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Windows\AndroidStudioProjects\LaboratorioCalificado003\BACKEND-FINANCIERA\env\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\Windows\AndroidStudioProjects\LaboratorioCalificado003\BACKEND-FINANCIERA\env\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\Windows\AndroidStudioProjects\LaboratorioCalificado003\BACKEND-FINANCIERA\env\Lib\site-packages\rest_framework\views.py", line 497, in dispatch
    self.initial(request, *args, **kwargs)
  File "C:\Users\Windows\AndroidStudioProjects\LaboratorioCalificado003\BACKEND-FINANCIERA\env\Lib\site-packages\rest_framework\views.py", line 415, in initial
    self.check_permissions(request)
  File "C:\Users\Windows\AndroidStudioProjects\LaboratorioCalificado003\BACKEND-FINANCIERA\env\Lib\site-packages\rest_framework\views.py", line 331, in check_permissions
    for permission in self.get_permissions():
                      ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Windows\AndroidStudioProjects\LaboratorioCalificado003\BACKEND-FINANCIERA\usuarios\views.py", line 26, in get_permissions
    if self.request.user.rol == "ADMIN":
       ^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'AnonymousUser' object has no attribute 'rol'
"GET /api/usuarios/ HTTP/1.1" 500 102021
Internal Server Error: /api/clientes/
Traceback (most recent call last):
  File "C:\Users\Windows\AndroidStudioProjects\LaboratorioCalificado003\BACKEND-FINANCIERA\env\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Windows\AndroidStudioProjects\LaboratorioCalificado003\BACKEND-FINANCIERA\env\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Windows\AndroidStudioProjects\LaboratorioCalificado003\BACKEND-FINANCIERA\env\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Windows\AndroidStudioProjects\LaboratorioCalificado003\BACKEND-FINANCIERA\env\Lib\site-packages\rest_framework\viewsets.py", line 124, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Windows\AndroidStudioProjects\LaboratorioCalificado003\BACKEND-FINANCIERA\env\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Windows\AndroidStudioProjects\LaboratorioCalificado003\BACKEND-FINANCIERA\env\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\Windows\AndroidStudioProjects\LaboratorioCalificado003\BACKEND-FINANCIERA\env\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\Windows\AndroidStudioProjects\LaboratorioCalificado003\BACKEND-FINANCIERA\env\Lib\site-packages\rest_framework\views.py", line 497, in dispatch
    self.initial(request, *args, **kwargs)
  File "C:\Users\Windows\AndroidStudioProjects\LaboratorioCalificado003\BACKEND-FINANCIERA\env\Lib\site-packages\rest_framework\views.py", line 415, in initial
    self.check_permissions(request)
  File "C:\Users\Windows\AndroidStudioProjects\LaboratorioCalificado003\BACKEND-FINANCIERA\env\Lib\site-packages\rest_framework\views.py", line 331, in check_permissions
    for permission in self.get_permissions():
                      ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Windows\AndroidStudioProjects\LaboratorioCalificado003\BACKEND-FINANCIERA\usuarios\views.py", line 37, in get_permissions
    if self.request.user.rol == "GERENTE":
       ^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'AnonymousUser' object has no attribute 'rol'
"GET /api/clientes/ HTTP/1.1" 500 102140
Internal Server Error: /api/facturas-clientes/
Traceback (most recent call last):
  File "C:\Users\Windows\AndroidStudioProjects\LaboratorioCalificado003\BACKEND-FINANCIERA\env\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Windows\AndroidStudioProjects\LaboratorioCalificado003\BACKEND-FINANCIERA\env\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Windows\AndroidStudioProjects\LaboratorioCalificado003\BACKEND-FINANCIERA\env\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Windows\AndroidStudioProjects\LaboratorioCalificado003\BACKEND-FINANCIERA\env\Lib\site-packages\rest_framework\viewsets.py", line 124, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Windows\AndroidStudioProjects\LaboratorioCalificado003\BACKEND-FINANCIERA\env\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Windows\AndroidStudioProjects\LaboratorioCalificado003\BACKEND-FINANCIERA\env\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\Windows\AndroidStudioProjects\LaboratorioCalificado003\BACKEND-FINANCIERA\env\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\Windows\AndroidStudioProjects\LaboratorioCalificado003\BACKEND-FINANCIERA\env\Lib\site-packages\rest_framework\views.py", line 497, in dispatch
    self.initial(request, *args, **kwargs)
  File "C:\Users\Windows\AndroidStudioProjects\LaboratorioCalificado003\BACKEND-FINANCIERA\env\Lib\site-packages\rest_framework\views.py", line 415, in initial
    self.check_permissions(request)
  File "C:\Users\Windows\AndroidStudioProjects\LaboratorioCalificado003\BACKEND-FINANCIERA\env\Lib\site-packages\rest_framework\views.py", line 331, in check_permissions
    for permission in self.get_permissions():
                      ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Windows\AndroidStudioProjects\LaboratorioCalificado003\BACKEND-FINANCIERA\usuarios\views.py", line 65, in get_permissions
    if self.request.user.rol == "CONTADOR":
       ^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'AnonymousUser' object has no attribute 'rol'
"GET /api/facturas-clientes/ HTTP/1.1" 500 102445
Internal Server Error: /api/facturas-clientes/
Traceback (most recent call last):
  File "C:\Users\Windows\AndroidStudioProjects\LaboratorioCalificado003\BACKEND-FINANCIERA\env\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Windows\AndroidStudioProjects\LaboratorioCalificado003\BACKEND-FINANCIERA\env\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Windows\AndroidStudioProjects\LaboratorioCalificado003\BACKEND-FINANCIERA\env\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Windows\AndroidStudioProjects\LaboratorioCalificado003\BACKEND-FINANCIERA\env\Lib\site-packages\rest_framework\viewsets.py", line 124, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Windows\AndroidStudioProjects\LaboratorioCalificado003\BACKEND-FINANCIERA\env\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Windows\AndroidStudioProjects\LaboratorioCalificado003\BACKEND-FINANCIERA\env\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\Windows\AndroidStudioProjects\LaboratorioCalificado003\BACKEND-FINANCIERA\env\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\Windows\AndroidStudioProjects\LaboratorioCalificado003\BACKEND-FINANCIERA\env\Lib\site-packages\rest_framework\views.py", line 497, in dispatch
    self.initial(request, *args, **kwargs)
  File "C:\Users\Windows\AndroidStudioProjects\LaboratorioCalificado003\BACKEND-FINANCIERA\env\Lib\site-packages\rest_framework\views.py", line 415, in initial
    self.check_permissions(request)
  File "C:\Users\Windows\AndroidStudioProjects\LaboratorioCalificado003\BACKEND-FINANCIERA\env\Lib\site-packages\rest_framework\views.py", line 331, in check_permissions
    for permission in self.get_permissions():
                      ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Windows\AndroidStudioProjects\LaboratorioCalificado003\BACKEND-FINANCIERA\usuarios\views.py", line 65, in get_permissions
    if self.request.user.rol == "CONTADOR":
       ^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'AnonymousUser' object has no attribute 'rol'
"GET /api/facturas-clientes/ HTTP/1.1" 500 102445
Internal Server Error: /api/usuarios/
Traceback (most recent call last):
  File "C:\Users\Windows\AndroidStudioProjects\LaboratorioCalificado003\BACKEND-FINANCIERA\env\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Windows\AndroidStudioProjects\LaboratorioCalificado003\BACKEND-FINANCIERA\env\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Windows\AndroidStudioProjects\LaboratorioCalificado003\BACKEND-FINANCIERA\env\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Windows\AndroidStudioProjects\LaboratorioCalificado003\BACKEND-FINANCIERA\env\Lib\site-packages\rest_framework\viewsets.py", line 124, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Windows\AndroidStudioProjects\LaboratorioCalificado003\BACKEND-FINANCIERA\env\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Windows\AndroidStudioProjects\LaboratorioCalificado003\BACKEND-FINANCIERA\env\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\Windows\AndroidStudioProjects\LaboratorioCalificado003\BACKEND-FINANCIERA\env\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\Windows\AndroidStudioProjects\LaboratorioCalificado003\BACKEND-FINANCIERA\env\Lib\site-packages\rest_framework\views.py", line 497, in dispatch
    self.initial(request, *args, **kwargs)
  File "C:\Users\Windows\AndroidStudioProjects\LaboratorioCalificado003\BACKEND-FINANCIERA\env\Lib\site-packages\rest_framework\views.py", line 415, in initial
    self.check_permissions(request)
  File "C:\Users\Windows\AndroidStudioProjects\LaboratorioCalificado003\BACKEND-FINANCIERA\env\Lib\site-packages\rest_framework\views.py", line 331, in check_permissions
    for permission in self.get_permissions():
                      ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Windows\AndroidStudioProjects\LaboratorioCalificado003\BACKEND-FINANCIERA\usuarios\views.py", line 26, in get_permissions
    if self.request.user.rol == "ADMIN":
       ^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'AnonymousUser' object has no attribute 'rol'
"GET /api/usuarios/ HTTP/1.1" 500 102021
Internal Server Error: /api/usuarios/
Traceback (most recent call last):
  File "C:\Users\Windows\AndroidStudioProjects\LaboratorioCalificado003\BACKEND-FINANCIERA\env\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Windows\AndroidStudioProjects\LaboratorioCalificado003\BACKEND-FINANCIERA\env\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Windows\AndroidStudioProjects\LaboratorioCalificado003\BACKEND-FINANCIERA\env\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Windows\AndroidStudioProjects\LaboratorioCalificado003\BACKEND-FINANCIERA\env\Lib\site-packages\rest_framework\viewsets.py", line 124, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Windows\AndroidStudioProjects\LaboratorioCalificado003\BACKEND-FINANCIERA\env\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Windows\AndroidStudioProjects\LaboratorioCalificado003\BACKEND-FINANCIERA\env\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\Windows\AndroidStudioProjects\LaboratorioCalificado003\BACKEND-FINANCIERA\env\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\Windows\AndroidStudioProjects\LaboratorioCalificado003\BACKEND-FINANCIERA\env\Lib\site-packages\rest_framework\views.py", line 497, in dispatch
    self.initial(request, *args, **kwargs)
  File "C:\Users\Windows\AndroidStudioProjects\LaboratorioCalificado003\BACKEND-FINANCIERA\env\Lib\site-packages\rest_framework\views.py", line 415, in initial
    self.check_permissions(request)
  File "C:\Users\Windows\AndroidStudioProjects\LaboratorioCalificado003\BACKEND-FINANCIERA\env\Lib\site-packages\rest_framework\views.py", line 331, in check_permissions
    for permission in self.get_permissions():
                      ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Windows\AndroidStudioProjects\LaboratorioCalificado003\BACKEND-FINANCIERA\usuarios\views.py", line 26, in get_permissions
    if self.request.user.rol == "ADMIN":
       ^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'User' object has no attribute 'rol'
"GET /api/usuarios/ HTTP/1.1" 500 102346
Internal Server Error: /api/usuarios/
Traceback (most recent call last):
  File "C:\Users\Windows\AndroidStudioProjects\LaboratorioCalificado003\BACKEND-FINANCIERA\env\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Windows\AndroidStudioProjects\LaboratorioCalificado003\BACKEND-FINANCIERA\env\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Windows\AndroidStudioProjects\LaboratorioCalificado003\BACKEND-FINANCIERA\env\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Windows\AndroidStudioProjects\LaboratorioCalificado003\BACKEND-FINANCIERA\env\Lib\site-packages\rest_framework\viewsets.py", line 124, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Windows\AndroidStudioProjects\LaboratorioCalificado003\BACKEND-FINANCIERA\env\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Windows\AndroidStudioProjects\LaboratorioCalificado003\BACKEND-FINANCIERA\env\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\Windows\AndroidStudioProjects\LaboratorioCalificado003\BACKEND-FINANCIERA\env\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\Windows\AndroidStudioProjects\LaboratorioCalificado003\BACKEND-FINANCIERA\env\Lib\site-packages\rest_framework\views.py", line 497, in dispatch
    self.initial(request, *args, **kwargs)
  File "C:\Users\Windows\AndroidStudioProjects\LaboratorioCalificado003\BACKEND-FINANCIERA\env\Lib\site-packages\rest_framework\views.py", line 415, in initial
    self.check_permissions(request)
  File "C:\Users\Windows\AndroidStudioProjects\LaboratorioCalificado003\BACKEND-FINANCIERA\env\Lib\site-packages\rest_framework\views.py", line 331, in check_permissions
    for permission in self.get_permissions():
                      ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Windows\AndroidStudioProjects\LaboratorioCalificado003\BACKEND-FINANCIERA\usuarios\views.py", line 26, in get_permissions
    if self.request.user.rol == "ADMIN":
       ^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'User' object has no attribute 'rol'
"GET /api/usuarios/ HTTP/1.1" 500 102346
Internal Server Error: /api/usuarios/
Traceback (most recent call last):
  File "C:\Users\Windows\AndroidStudioProjects\LaboratorioCalificado003\BACKEND-FINANCIERA\env\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Windows\AndroidStudioProjects\LaboratorioCalificado003\BACKEND-FINANCIERA\env\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Windows\AndroidStudioProjects\LaboratorioCalificado003\BACKEND-FINANCIERA\env\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Windows\AndroidStudioProjects\LaboratorioCalificado003\BACKEND-FINANCIERA\env\Lib\site-packages\rest_framework\viewsets.py", line 124, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Windows\AndroidStudioProjects\LaboratorioCalificado003\BACKEND-FINANCIERA\env\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Windows\AndroidStudioProjects\LaboratorioCalificado003\BACKEND-FINANCIERA\env\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\Windows\AndroidStudioProjects\LaboratorioCalificado003\BACKEND-FINANCIERA\env\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\Windows\AndroidStudioProjects\LaboratorioCalificado003\BACKEND-FINANCIERA\env\Lib\site-packages\rest_framework\views.py", line 497, in dispatch
    self.initial(request, *args, **kwargs)
  File "C:\Users\Windows\AndroidStudioProjects\LaboratorioCalificado003\BACKEND-FINANCIERA\env\Lib\site-packages\rest_framework\views.py", line 415, in initial
    self.check_permissions(request)
  File "C:\Users\Windows\AndroidStudioProjects\LaboratorioCalificado003\BACKEND-FINANCIERA\env\Lib\site-packages\rest_framework\views.py", line 331, in check_permissions
    for permission in self.get_permissions():
                      ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Windows\AndroidStudioProjects\LaboratorioCalificado003\BACKEND-FINANCIERA\usuarios\views.py", line 26, in get_permissions
    if self.request.user.rol == "ADMIN":
       ^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'User' object has no attribute 'rol'
"GET /api/usuarios/ HTTP/1.1" 500 102346
Internal Server Error: /api/usuarios/
Traceback (most recent call last):
  File "C:\Users\Windows\AndroidStudioProjects\LaboratorioCalificado003\BACKEND-FINANCIERA\env\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Windows\AndroidStudioProjects\LaboratorioCalificado003\BACKEND-FINANCIERA\env\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Windows\AndroidStudioProjects\LaboratorioCalificado003\BACKEND-FINANCIERA\env\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Windows\AndroidStudioProjects\LaboratorioCalificado003\BACKEND-FINANCIERA\env\Lib\site-packages\rest_framework\viewsets.py", line 124, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Windows\AndroidStudioProjects\LaboratorioCalificado003\BACKEND-FINANCIERA\env\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Windows\AndroidStudioProjects\LaboratorioCalificado003\BACKEND-FINANCIERA\env\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\Windows\AndroidStudioProjects\LaboratorioCalificado003\BACKEND-FINANCIERA\env\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\Windows\AndroidStudioProjects\LaboratorioCalificado003\BACKEND-FINANCIERA\env\Lib\site-packages\rest_framework\views.py", line 497, in dispatch
    self.initial(request, *args, **kwargs)
  File "C:\Users\Windows\AndroidStudioProjects\LaboratorioCalificado003\BACKEND-FINANCIERA\env\Lib\site-packages\rest_framework\views.py", line 415, in initial
    self.check_permissions(request)
  File "C:\Users\Windows\AndroidStudioProjects\LaboratorioCalificado003\BACKEND-FINANCIERA\env\Lib\site-packages\rest_framework\views.py", line 331, in check_permissions
    for permission in self.get_permissions():
                      ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Windows\AndroidStudioProjects\LaboratorioCalificado003\BACKEND-FINANCIERA\usuarios\views.py", line 26, in get_permissions
    if self.request.user.rol == "ADMIN":
       ^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'User' object has no attribute 'rol'
"GET /api/usuarios/ HTTP/1.1" 500 145
Internal Server Error: /api/clientes/
Traceback (most recent call last):
  File "C:\Users\Windows\AndroidStudioProjects\LaboratorioCalificado003\BACKEND-FINANCIERA\env\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Windows\AndroidStudioProjects\LaboratorioCalificado003\BACKEND-FINANCIERA\env\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Windows\AndroidStudioProjects\LaboratorioCalificado003\BACKEND-FINANCIERA\env\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Windows\AndroidStudioProjects\LaboratorioCalificado003\BACKEND-FINANCIERA\env\Lib\site-packages\rest_framework\viewsets.py", line 124, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Windows\AndroidStudioProjects\LaboratorioCalificado003\BACKEND-FINANCIERA\env\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Windows\AndroidStudioProjects\LaboratorioCalificado003\BACKEND-FINANCIERA\env\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\Windows\AndroidStudioProjects\LaboratorioCalificado003\BACKEND-FINANCIERA\env\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\Windows\AndroidStudioProjects\LaboratorioCalificado003\BACKEND-FINANCIERA\env\Lib\site-packages\rest_framework\views.py", line 497, in dispatch
    self.initial(request, *args, **kwargs)
  File "C:\Users\Windows\AndroidStudioProjects\LaboratorioCalificado003\BACKEND-FINANCIERA\env\Lib\site-packages\rest_framework\views.py", line 415, in initial
    self.check_permissions(request)
  File "C:\Users\Windows\AndroidStudioProjects\LaboratorioCalificado003\BACKEND-FINANCIERA\env\Lib\site-packages\rest_framework\views.py", line 331, in check_permissions
    for permission in self.get_permissions():
                      ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Windows\AndroidStudioProjects\LaboratorioCalificado003\BACKEND-FINANCIERA\usuarios\views.py", line 37, in get_permissions
    if self.request.user.rol == "GERENTE":
       ^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'User' object has no attribute 'rol'
"GET /api/clientes/ HTTP/1.1" 500 145
Internal Server Error: /api/usuarios/
Traceback (most recent call last):
  File "C:\Users\Windows\AndroidStudioProjects\LaboratorioCalificado003\BACKEND-FINANCIERA\env\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Windows\AndroidStudioProjects\LaboratorioCalificado003\BACKEND-FINANCIERA\env\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Windows\AndroidStudioProjects\LaboratorioCalificado003\BACKEND-FINANCIERA\env\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Windows\AndroidStudioProjects\LaboratorioCalificado003\BACKEND-FINANCIERA\env\Lib\site-packages\rest_framework\viewsets.py", line 124, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Windows\AndroidStudioProjects\LaboratorioCalificado003\BACKEND-FINANCIERA\env\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Windows\AndroidStudioProjects\LaboratorioCalificado003\BACKEND-FINANCIERA\env\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\Windows\AndroidStudioProjects\LaboratorioCalificado003\BACKEND-FINANCIERA\env\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\Windows\AndroidStudioProjects\LaboratorioCalificado003\BACKEND-FINANCIERA\env\Lib\site-packages\rest_framework\views.py", line 497, in dispatch
    self.initial(request, *args, **kwargs)
  File "C:\Users\Windows\AndroidStudioProjects\LaboratorioCalificado003\BACKEND-FINANCIERA\env\Lib\site-packages\rest_framework\views.py", line 415, in initial
    self.check_permissions(request)
  File "C:\Users\Windows\AndroidStudioProjects\LaboratorioCalificado003\BACKEND-FINANCIERA\env\Lib\site-packages\rest_framework\views.py", line 331, in check_permissions
    for permission in self.get_permissions():
                      ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Windows\AndroidStudioProjects\LaboratorioCalificado003\BACKEND-FINANCIERA\usuarios\views.py", line 26, in get_permissions
    if self.request.user.rol == "ADMIN":
       ^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'User' object has no attribute 'rol'
"GET /api/usuarios/ HTTP/1.1" 500 145
Internal Server Error: /api/clientes/
Traceback (most recent call last):
  File "C:\Users\Windows\AndroidStudioProjects\LaboratorioCalificado003\BACKEND-FINANCIERA\env\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Windows\AndroidStudioProjects\LaboratorioCalificado003\BACKEND-FINANCIERA\env\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Windows\AndroidStudioProjects\LaboratorioCalificado003\BACKEND-FINANCIERA\env\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Windows\AndroidStudioProjects\LaboratorioCalificado003\BACKEND-FINANCIERA\env\Lib\site-packages\rest_framework\viewsets.py", line 124, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Windows\AndroidStudioProjects\LaboratorioCalificado003\BACKEND-FINANCIERA\env\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Windows\AndroidStudioProjects\LaboratorioCalificado003\BACKEND-FINANCIERA\env\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\Windows\AndroidStudioProjects\LaboratorioCalificado003\BACKEND-FINANCIERA\env\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\Windows\AndroidStudioProjects\LaboratorioCalificado003\BACKEND-FINANCIERA\env\Lib\site-packages\rest_framework\views.py", line 497, in dispatch
    self.initial(request, *args, **kwargs)
  File "C:\Users\Windows\AndroidStudioProjects\LaboratorioCalificado003\BACKEND-FINANCIERA\env\Lib\site-packages\rest_framework\views.py", line 415, in initial
    self.check_permissions(request)
  File "C:\Users\Windows\AndroidStudioProjects\LaboratorioCalificado003\BACKEND-FINANCIERA\env\Lib\site-packages\rest_framework\views.py", line 331, in check_permissions
    for permission in self.get_permissions():
                      ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Windows\AndroidStudioProjects\LaboratorioCalificado003\BACKEND-FINANCIERA\usuarios\views.py", line 37, in get_permissions
    if self.request.user.rol == "GERENTE":
       ^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'User' object has no attribute 'rol'
"GET /api/clientes/ HTTP/1.1" 500 145
Internal Server Error: /api/usuarios/
Traceback (most recent call last):
  File "C:\Users\Windows\AndroidStudioProjects\LaboratorioCalificado003\BACKEND-FINANCIERA\env\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Windows\AndroidStudioProjects\LaboratorioCalificado003\BACKEND-FINANCIERA\env\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Windows\AndroidStudioProjects\LaboratorioCalificado003\BACKEND-FINANCIERA\env\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Windows\AndroidStudioProjects\LaboratorioCalificado003\BACKEND-FINANCIERA\env\Lib\site-packages\rest_framework\viewsets.py", line 124, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Windows\AndroidStudioProjects\LaboratorioCalificado003\BACKEND-FINANCIERA\env\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Windows\AndroidStudioProjects\LaboratorioCalificado003\BACKEND-FINANCIERA\env\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\Windows\AndroidStudioProjects\LaboratorioCalificado003\BACKEND-FINANCIERA\env\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\Windows\AndroidStudioProjects\LaboratorioCalificado003\BACKEND-FINANCIERA\env\Lib\site-packages\rest_framework\views.py", line 497, in dispatch
    self.initial(request, *args, **kwargs)
  File "C:\Users\Windows\AndroidStudioProjects\LaboratorioCalificado003\BACKEND-FINANCIERA\env\Lib\site-packages\rest_framework\views.py", line 415, in initial
    self.check_permissions(request)
  File "C:\Users\Windows\AndroidStudioProjects\LaboratorioCalificado003\BACKEND-FINANCIERA\env\Lib\site-packages\rest_framework\views.py", line 331, in check_permissions
    for permission in self.get_permissions():
                      ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Windows\AndroidStudioProjects\LaboratorioCalificado003\BACKEND-FINANCIERA\usuarios\views.py", line 26, in get_permissions
    if self.request.user.rol == "ADMIN":
       ^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'User' object has no attribute 'rol'
"GET /api/usuarios/ HTTP/1.1" 500 145
Internal Server Error: /api/usuarios/token/
Traceback (most recent call last):
  File "C:\Users\Windows\AndroidStudioProjects\LaboratorioCalificado003\BACKEND-FINANCIERA\env\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Windows\AndroidStudioProjects\LaboratorioCalificado003\BACKEND-FINANCIERA\env\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Windows\AndroidStudioProjects\LaboratorioCalificado003\BACKEND-FINANCIERA\env\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Windows\AndroidStudioProjects\LaboratorioCalificado003\BACKEND-FINANCIERA\env\Lib\site-packages\rest_framework\viewsets.py", line 124, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Windows\AndroidStudioProjects\LaboratorioCalificado003\BACKEND-FINANCIERA\env\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Windows\AndroidStudioProjects\LaboratorioCalificado003\BACKEND-FINANCIERA\env\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\Windows\AndroidStudioProjects\LaboratorioCalificado003\BACKEND-FINANCIERA\env\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\Windows\AndroidStudioProjects\LaboratorioCalificado003\BACKEND-FINANCIERA\env\Lib\site-packages\rest_framework\views.py", line 497, in dispatch
    self.initial(request, *args, **kwargs)
  File "C:\Users\Windows\AndroidStudioProjects\LaboratorioCalificado003\BACKEND-FINANCIERA\env\Lib\site-packages\rest_framework\views.py", line 415, in initial
    self.check_permissions(request)
  File "C:\Users\Windows\AndroidStudioProjects\LaboratorioCalificado003\BACKEND-FINANCIERA\env\Lib\site-packages\rest_framework\views.py", line 331, in check_permissions
    for permission in self.get_permissions():
                      ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Windows\AndroidStudioProjects\LaboratorioCalificado003\BACKEND-FINANCIERA\usuarios\views.py", line 26, in get_permissions
    if self.request.user.rol == "ADMIN":
       ^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'User' object has no attribute 'rol'
"GET /api/usuarios/token/ HTTP/1.1" 500 145
Internal Server Error: /api/usuarios/
Traceback (most recent call last):
  File "C:\Users\Windows\AndroidStudioProjects\LaboratorioCalificado003\BACKEND-FINANCIERA\env\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Windows\AndroidStudioProjects\LaboratorioCalificado003\BACKEND-FINANCIERA\env\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Windows\AndroidStudioProjects\LaboratorioCalificado003\BACKEND-FINANCIERA\env\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Windows\AndroidStudioProjects\LaboratorioCalificado003\BACKEND-FINANCIERA\env\Lib\site-packages\rest_framework\viewsets.py", line 124, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Windows\AndroidStudioProjects\LaboratorioCalificado003\BACKEND-FINANCIERA\env\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Windows\AndroidStudioProjects\LaboratorioCalificado003\BACKEND-FINANCIERA\env\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\Windows\AndroidStudioProjects\LaboratorioCalificado003\BACKEND-FINANCIERA\env\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\Windows\AndroidStudioProjects\LaboratorioCalificado003\BACKEND-FINANCIERA\env\Lib\site-packages\rest_framework\views.py", line 497, in dispatch
    self.initial(request, *args, **kwargs)
  File "C:\Users\Windows\AndroidStudioProjects\LaboratorioCalificado003\BACKEND-FINANCIERA\env\Lib\site-packages\rest_framework\views.py", line 415, in initial
    self.check_permissions(request)
  File "C:\Users\Windows\AndroidStudioProjects\LaboratorioCalificado003\BACKEND-FINANCIERA\env\Lib\site-packages\rest_framework\views.py", line 331, in check_permissions
    for permission in self.get_permissions():
                      ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Windows\AndroidStudioProjects\LaboratorioCalificado003\BACKEND-FINANCIERA\usuarios\views.py", line 26, in get_permissions
    if self.request.user.rol == "ADMIN":
       ^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'User' object has no attribute 'rol'
"GET /api/usuarios/ HTTP/1.1" 500 145
Invalid HTTP_HOST header: '127.0.0.1:8000'. You may need to add '127.0.0.1' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "C:\Users\Windows\AndroidStudioProjects\LaboratorioCalificado003\BACKEND-FINANCIERA\env\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Windows\AndroidStudioProjects\LaboratorioCalificado003\BACKEND-FINANCIERA\env\Lib\site-packages\django\utils\deprecation.py", line 128, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Windows\AndroidStudioProjects\LaboratorioCalificado003\BACKEND-FINANCIERA\env\Lib\site-packages\django\middleware\common.py", line 48, in process_request
    host = request.get_host()
           ^^^^^^^^^^^^^^^^^^
  File "C:\Users\Windows\AndroidStudioProjects\LaboratorioCalificado003\BACKEND-FINANCIERA\env\Lib\site-packages\django\http\request.py", line 151, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '127.0.0.1:8000'. You may need to add '127.0.0.1' to ALLOWED_HOSTS.
Internal Server Error: /api/token
Traceback (most recent call last):
  File "C:\Users\Windows\AndroidStudioProjects\LaboratorioCalificado003\BACKEND-FINANCIERA\env\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Windows\AndroidStudioProjects\LaboratorioCalificado003\BACKEND-FINANCIERA\env\Lib\site-packages\django\utils\deprecation.py", line 131, in __call__
    response = self.process_response(request, response)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Windows\AndroidStudioProjects\LaboratorioCalificado003\BACKEND-FINANCIERA\env\Lib\site-packages\django\middleware\common.py", line 108, in process_response
    return self.response_redirect_class(self.get_full_path_with_slash(request))
                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Windows\AndroidStudioProjects\LaboratorioCalificado003\BACKEND-FINANCIERA\env\Lib\site-packages\django\middleware\common.py", line 87, in get_full_path_with_slash
    raise RuntimeError(
RuntimeError: You called this URL via POST, but the URL doesn't end in a slash and you have APPEND_SLASH set. Django can't redirect to the slash URL while maintaining POST data. Change your form to point to localhost:8000/api/token/ (note the trailing slash), or set APPEND_SLASH=False in your Django settings.
"POST /api/token HTTP/1.1" 500 72524
